name: WordPress Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'   # 02:00 JST 毎日

jobs:
  post:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # setup-python を削除／コメントアウトして OK
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Install deps (system python)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests

          # 追加：キーワード収集
      - name: Collect Google suggest keywords
        env:
          SEED_KW: ${{ secrets.SEED_KW }}   # 任意。無ければデフォルト
        run: python3 crawler/suggest.py
      
      - name: Clean keywords
        run: python3 crawler/clean_keywords.py
        
      - name: Crawl site & extract HTML
        env:
          SITE_BASE: ${{ vars.SITE_BASE }}
        run: python3 crawler/crawl_site.py $SITE_BASE

      - name: Upload corpus
        uses: actions/upload-artifact@v4
        with:
          name: corpus-${{ github.run_number }}
          path: data/corpus.jsonl
          retention-days: 5

      # 既存：記事生成 & 投稿
      - name: Run posting script
        env:
          WP_URL:  ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          KW:      ${{ secrets.KW }}         # ← 後で keywords.csv から読むよう拡張予定
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 pipeline/run.py



