name: WordPress Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'   # 02:00 JST 毎日

jobs:
  post:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # setup-python を削除／コメントアウトして OK
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Install deps (system python)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests

      - name: Run posting script
        env:
          WP_URL:  ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          KW:      ${{ secrets.KW }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 pipeline/run.py



