name: WordPress Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'   # 02:00 JST 毎日

jobs:
  post:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # setup-python を削除／コメントアウトして OK
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
    
      - name: Install Rust toolchain (arm64)
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: arch -arm64 brew install rust

      - name: Install deps (system python)
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
        run: |
          set -x
          python3 -m pip install --upgrade pip
          python3 -m pip install \
            --no-binary charset-normalizer,regex \
            "charset-normalizer<3.4" regex \
            requests "trafilatura[all]" tqdm \
            openai==1.10.0 "httpx<0.25" \
            "numpy<2.0" \
            "pydantic<2" chromadb tiktoken

      # ここからキーワード処理
      - name: Collect Google suggest keywords
        env:
          SEED_KW: ${{ secrets.SEED_KW }}
        run: python3 crawler/suggest.py
      
      - name: Clean keywords
        run: python3 crawler/clean_keywords.py
        
      - name: Crawl site & extract HTML
        env:
          SITE_BASE: ${{ vars.SITE_BASE }}   # Repository Variables に設定したURL
        run: python3 crawler/crawl_site.py    # 引数は省略、環境変数を使う

      - name: Upload corpus
        uses: actions/upload-artifact@v4
        with:
          name: corpus-${{ github.run_number }}
          path: data/corpus.jsonl
          retention-days: 5

      - name: Embed corpus & store to Chroma
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 pipeline/embed_corpus.py

      # 既存：記事生成 & 投稿
      - name: Run posting script
        env:
          WP_URL:  ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          KW:      ${{ secrets.KW }}         # ← 後で keywords.csv から読むよう拡張予定
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 pipeline/run.py



